insert into INSURANCE_POLICY(POLICY_ID,POLICY_NAME,POLICY_PRICE)values(101,'LIC',500.25);
insert into INSURANCE_POLICY(POLICY_ID,POLICY_NAME,POLICY_PRICE)values(102,'HDFC',700.25);
insert into INSURANCE_POLICY(POLICY_ID,POLICY_NAME,POLICY_PRICE)values(103,'SBI',600.25);
insert into INSURANCE_POLICY(POLICY_ID,POLICY_NAME,POLICY_PRICE)values(104,'BAJAJ',800.25);
